# Generated by Django 5.2.12 on 2026-03-14 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('code', models.CharField(max_length=10, unique=True)),
                ('manager_name', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(2)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(2)])),
                ('job_title', models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(2)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hire_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
